services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - "4000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=loic
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=loic
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./data:/var/lib/postgresql/data
